Citizen.CreateThread(function()
	AddTextEntry('code310charg', 'Charger 310')
	AddTextEntry('code314charg', 'Charger 314')
	AddTextEntry('code314tahoe', 'Tahoe 314')
	AddTextEntry('code316impala', 'Impala')
	AddTextEntry("code318charg", 'Charger 318')
	AddTextEntry('code318chargk9', 'Charger 318 K9')
	AddTextEntry('code318tahoek9', 'Tahoe 318 K9')
	AddTextEntry('code319silv', 'Silverado')
	AddTextEntry('code320exp', 'Explorer 320')
	AddTextEntry('code3bmw', 'BMW MOTO')
	AddTextEntry('code3boat', 'Lod')
	AddTextEntry('code3camero', 'Camaro')
	AddTextEntry('code3cap', 'Caprice')
	AddTextEntry('code3cvpi', 'Victoria')
	AddTextEntry('code3durango', 'Durango')
	AddTextEntry('code3f150', 'Ford 150')
	AddTextEntry('code3f250', 'Ford 250')
	AddTextEntry('code3fpis', 'Fpis')
	AddTextEntry('code3gator', 'Jezdítko')
	AddTextEntry('code3harley', 'Choppa')
	AddTextEntry('code3mustang', 'Mustang')
	AddTextEntry('code3trailer', 'Vozik LOD')
	AddTextEntry('code3trailer2', 'Vozík plotna')
end)

